theme: minima
title: "Zach's Test Page"
author: Zach
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This Page has been created for tutorial purposes

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  ZachWill-RMIT # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
